name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: devops_library_branch
    displayName: DevOps Library Branch
    type: string
    default: main
  - name: run_github_security_scan
    type: boolean
    displayName: Run GitHub Advanced Security Scan
    default: true

variables:
  - name: vstsFeed
    value: "0e030eb0-cb72-4f42-b99a-26e6544271c3/0a3e0ad2-23b6-4e8b-ae12-cd6d01fe97e7"
  - name: project
    value: "**/Rsp.Logging.csproj"
  - name: solution
    value: "**/*.sln"
  - name: buildConfiguration
    value: "Release"

resources:
  repositories:
    - repository: library
      type: git
      name: DevOps/rsp-azure-devops-library
      ref: ${{ parameters.devops_library_branch }}

stages:
  - template: jobs/artifact.yaml@library
    parameters:
      run_github_security_scan: ${{ parameters.run_github_security_scan }}